### ISSUE TITLE
Can't find my guild on gw.swop.one

### ISSUE THREAD

**Issue by torkilt** [Xzandro/SwagLogger#1]
I'm running the latest Summoners War Exporter and I get "GetGuildWarBattleLogByGuildId logged successfully" when I visit Attack and Defense tabs. SwagLogger is enabled but I can't find my guild on gw.swop.one. 

Running Windows 10. Any known problems, like Windows firewall or something?`

Thanks,

Torkil

**Comment by Xzandro** [comment]
Not that I know of. Make sure you selected the right region.

**Comment by torkilt** [comment]
I checked all regions several times before I posted, no dice. Oh well.

Thanks,

Torkil

**Comment by torkilt** [comment]
Any other suggestions? It still doesn't log anything, or at least it's not showing on the website. 

In the log it also seems fine. Could you maybe check the server log?

Snippet:
`
API Command: GetGuildWarBattleLogByGuildId - Thu May 11 2017 22:06:23 GMT+0200 (Romance Summer Time)
Request: 
{"command":"GetGuildWarBattleLogByGuildId","wizard_id":4035143,"session_key":"686e424ecf922c69b36804964faf0c","proto_ver":10860,"infocsv":"3.00.87","channel_uid":182866272,"ts_val":1161544371,"target_guild_id":96948,"log_type":1}
Response: 
{
[snip]
}
`

**Comment by Xzandro** [comment]
It seems to work for everyone else so I honestly dont really know where the problem is. But you could tell me your region and your guild name to look for myself if the guild exists or not.

**Comment by torkilt** [comment]
Europe/THE EREDAR

In the log it shows as 'guild_name":"THE EREDAR"'

**Comment by Xzandro** [comment]
Hmm, no. There is no guild with such a name in the logs and in the database. I honestly have no idea what the error could be. I asked a few people if they had any issues recently and it worked like a charm for everyone. So if you really use https://github.com/Xzandro/sw-exporter and have the SwagLogger plugin activated I really dont see any problem sources. Sorry.

**Comment by torkilt** [comment]
I (re)downloaded the portable version from https://github.com/Xzandro/sw-exporter/releases/tag/0.0.17, still no dice. Plugin is activated, and stuff shows up in my log, so decidedly weird. I guess I'll have to put a proxy in front of sw-exporter or something, to see what's going on

**Comment by Xzandro** [comment]
I mean you could give the complete response data of that event so I can fire it to the server myself and see how it goes. If it works for me its something really weird on your end and if it doesnt work, there is something wrong with my server side code.

**Comment by torkilt** [comment]
`
API Command: GetGuildWarBattleLogByGuildId - Thu May 11 2017 22:06:23 GMT+0200 (Romance Summer Time)
Request: 
{"command":"GetGuildWarBattleLogByGuildId","wizard_id":4035143,"session_key":"686e424ecf922c69b36804964faf0c","proto_ver":10860,"infocsv":"3.00.87","channel_uid":182866272,"ts_val":1161544371,"target_guild_id":96948,"log_type":1}
Response: 
{"command":"GetGuildWarBattleLogByGuildId","ret_code":0,"log_type":1,"battle_log_list_group":[{"opp_guild_info":{"guild_id":63877,"name":"crevardsuisse","master_wizard_id":809807,"master_channel_uid":135566950,"master_wizard_name":"psycoterrorist","master_wizard_level":50},"battle_log_list":[{"rid":4757445,"battle_time":42,"log_type":1,"match_id":10145961,"league_type":100,"wizard_id":2344269,"wizard_level":50,"channel_uid":171429674,"wizard_name":"mei0404","win_count":1,"draw_count":0,"lose_count":1,"result":[2,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":8,"opp_wizard_id":68930,"opp_channel_uid":151324622,"opp_wizard_level":50,"opp_wizard_name":"Shin'Luristan","opp_guild_id":63877,"opp_guild_name":"crevardsuisse","battle_end":1494533140},{"rid":4751823,"battle_time":339,"log_type":1,"match_id":10145961,"league_type":100,"wizard_id":2344269,"wizard_level":50,"channel_uid":171429674,"wizard_name":"mei0404","win_count":1,"draw_count":0,"lose_count":1,"result":[2,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":7,"opp_wizard_id":3743507,"opp_channel_uid":181605123,"opp_wizard_level":50,"opp_wizard_name":"Warløck","opp_guild_id":63877,"opp_guild_name":"crevardsuisse","battle_end":1494532843},{"rid":4746579,"battle_time":619,"log_type":1,"match_id":10145961,"league_type":100,"wizard_id":2344269,"wizard_level":50,"channel_uid":171429674,"wizard_name":"mei0404","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":12,"opp_wizard_id":4239315,"opp_channel_uid":190630158,"opp_wizard_level":50,"opp_wizard_name":"Fantix5","opp_guild_id":63877,"opp_guild_name":"crevardsuisse","battle_end":1494532563},{"rid":4739611,"battle_time":1004,"log_type":1,"match_id":10145961,"league_type":100,"wizard_id":4035143,"wizard_level":50,"channel_uid":182866272,"wizard_name":"Ahten","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":16,"opp_wizard_id":68930,"opp_channel_uid":151324622,"opp_wizard_level":50,"opp_wizard_name":"Shin'Luristan","opp_guild_id":63877,"opp_guild_name":"crevardsuisse","battle_end":1494532178},{"rid":4736821,"battle_time":1154,"log_type":1,"match_id":10145961,"league_type":100,"wizard_id":4035143,"wizard_level":50,"channel_uid":182866272,"wizard_name":"Ahten","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":14,"opp_wizard_id":1989756,"opp_channel_uid":167449411,"opp_wizard_level":50,"opp_wizard_name":"Le_chevreuil","opp_guild_id":63877,"opp_guild_name":"crevardsuisse","battle_end":1494532028},{"rid":4732907,"battle_time":1369,"log_type":1,"match_id":10145961,"league_type":100,"wizard_id":4035143,"wizard_level":50,"channel_uid":182866272,"wizard_name":"Ahten","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":12,"opp_wizard_id":2817853,"opp_channel_uid":188316423,"opp_wizard_level":50,"opp_wizard_name":"Ashrog","opp_guild_id":63877,"opp_guild_name":"crevardsuisse","battle_end":1494531813},{"rid":4691139,"battle_time":3485,"log_type":1,"match_id":10145961,"league_type":100,"wizard_id":4666740,"wizard_level":50,"channel_uid":185699041,"wizard_name":"DmcRaze","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":16,"opp_wizard_id":68930,"opp_channel_uid":151324622,"opp_wizard_level":50,"opp_wizard_name":"Shin'Luristan","opp_guild_id":63877,"opp_guild_name":"crevardsuisse","battle_end":1494529697},{"rid":4688563,"battle_time":3618,"log_type":1,"match_id":10145961,"league_type":100,"wizard_id":4666740,"wizard_level":50,"channel_uid":185699041,"wizard_name":"DmcRaze","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":14,"opp_wizard_id":3743507,"opp_channel_uid":181605123,"opp_wizard_level":50,"opp_wizard_name":"Warløck","opp_guild_id":63877,"opp_guild_name":"crevardsuisse","battle_end":1494529564},{"rid":4685927,"battle_time":3750,"log_type":1,"match_id":10145961,"league_type":100,"wizard_id":4666740,"wizard_level":50,"channel_uid":185699041,"wizard_name":"DmcRaze","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":12,"opp_wizard_id":3119577,"opp_channel_uid":177576588,"opp_wizard_level":50,"opp_wizard_name":"lag46","opp_guild_id":63877,"opp_guild_name":"crevardsuisse","battle_end":1494529432},{"rid":4640239,"battle_time":6144,"log_type":1,"match_id":10145961,"league_type":100,"wizard_id":3253099,"wizard_level":50,"channel_uid":178457033,"wizard_name":"Raizcap","win_count":1,"draw_count":0,"lose_count":1,"result":[2,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":8,"opp_wizard_id":83119,"opp_channel_uid":123649925,"opp_wizard_level":50,"opp_wizard_name":"Shin'D.Bubu","opp_guild_id":63877,"opp_guild_name":"crevardsuisse","battle_end":1494527038},{"rid":4635953,"battle_time":6344,"log_type":1,"match_id":10145961,"league_type":100,"wizard_id":3253099,"wizard_level":50,"channel_uid":178457033,"wizard_name":"Raizcap","win_count":0,"draw_count":0,"lose_count":2,"result":[2,2],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":0,"opp_wizard_id":3743507,"opp_channel_uid":181605123,"opp_wizard_level":50,"opp_wizard_name":"Warløck","opp_guild_id":63877,"opp_guild_name":"crevardsuisse","battle_end":1494526838},{"rid":4631345,"battle_time":6567,"log_type":1,"match_id":10145961,"league_type":100,"wizard_id":1231347,"wizard_level":50,"channel_uid":161466035,"wizard_name":"Awing","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":10,"opp_wizard_id":454636,"opp_channel_uid":155953062,"opp_wizard_level":50,"opp_wizard_name":"gamj","opp_guild_id":63877,"opp_guild_name":"crevardsuisse","battle_end":1494526615},{"rid":4627295,"battle_time":6761,"log_type":1,"match_id":10145961,"league_type":100,"wizard_id":1231347,"wizard_level":50,"channel_uid":161466035,"wizard_name":"Awing","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":16,"opp_wizard_id":809807,"opp_channel_uid":135566950,"opp_wizard_level":50,"opp_wizard_name":"psycoterrorist","opp_guild_id":63877,"opp_guild_name":"crevardsuisse","battle_end":1494526421},{"rid":4626969,"battle_time":6776,"log_type":1,"match_id":10145961,"league_type":100,"wizard_id":3253099,"wizard_level":50,"channel_uid":178457033,"wizard_name":"Raizcap","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":10,"opp_wizard_id":2409011,"opp_channel_uid":172445974,"opp_wizard_level":40,"opp_wizard_name":"Warsaat","opp_guild_id":63877,"opp_guild_name":"crevardsuisse","battle_end":1494526406},{"rid":4621737,"battle_time":7038,"log_type":1,"match_id":10145961,"league_type":100,"wizard_id":1231347,"wizard_level":50,"channel_uid":161466035,"wizard_name":"Awing","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":16,"opp_wizard_id":83119,"opp_channel_uid":123649925,"opp_wizard_level":50,"opp_wizard_name":"Shin'D.Bubu","opp_guild_id":63877,"opp_guild_name":"crevardsuisse","battle_end":1494526144},{"rid":4621341,"battle_time":7056,"log_type":1,"match_id":10145961,"league_type":100,"wizard_id":4847862,"wizard_level":50,"channel_uid":187072296,"wizard_name":"Kapaya","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":14,"opp_wizard_id":2129601,"opp_channel_uid":168975844,"opp_wizard_level":50,"opp_wizard_name":"○Cliché○","opp_guild_id":63877,"opp_guild_name":"crevardsuisse","battle_end":1494526126},{"rid":4618285,"battle_time":7208,"log_type":1,"match_id":10145961,"league_type":100,"wizard_id":4847862,"wizard_level":50,"channel_uid":187072296,"wizard_name":"Kapaya","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":16,"opp_wizard_id":83119,"opp_channel_uid":123649925,"opp_wizard_level":50,"opp_wizard_name":"Shin'D.Bubu","opp_guild_id":63877,"opp_guild_name":"crevardsuisse","battle_end":1494525974}]},{"opp_guild_info":{"guild_id":54912,"name":"VulKlán","master_wizard_id":732196,"master_channel_uid":157657037,"master_wizard_name":"Godhunter","master_wizard_level":50},"battle_log_list":[{"rid":4541925,"battle_time":11211,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":4666740,"wizard_level":50,"channel_uid":185699041,"wizard_name":"DmcRaze","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":10,"opp_wizard_id":425044,"opp_channel_uid":136873074,"opp_wizard_level":50,"opp_wizard_name":"Gutshun","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494521971},{"rid":4540349,"battle_time":11298,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":4666740,"wizard_level":50,"channel_uid":185699041,"wizard_name":"DmcRaze","win_count":0,"draw_count":0,"lose_count":2,"result":[2,2],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":0,"opp_wizard_id":1629481,"opp_channel_uid":165345207,"opp_wizard_level":50,"opp_wizard_name":"*LeTsKo*","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494521884},{"rid":4537091,"battle_time":11481,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":4666740,"wizard_level":50,"channel_uid":185699041,"wizard_name":"DmcRaze","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":14,"opp_wizard_id":33594,"opp_channel_uid":154284156,"opp_wizard_level":50,"opp_wizard_name":"Szalesz","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494521701},{"rid":4489715,"battle_time":14129,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":4997874,"wizard_level":50,"channel_uid":188101483,"wizard_name":"Mlpzaqnkoxsw","win_count":1,"draw_count":0,"lose_count":1,"result":[1,2],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":6,"opp_wizard_id":732196,"opp_channel_uid":157657037,"opp_wizard_level":50,"opp_wizard_name":"Godhunter","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494519053},{"rid":4487265,"battle_time":14263,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":4997874,"wizard_level":50,"channel_uid":188101483,"wizard_name":"Mlpzaqnkoxsw","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":10,"opp_wizard_id":1370484,"opp_channel_uid":163208333,"opp_wizard_level":50,"opp_wizard_name":"cpt_n3m0","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494518919},{"rid":4483825,"battle_time":14457,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":4997874,"wizard_level":50,"channel_uid":188101483,"wizard_name":"Mlpzaqnkoxsw","win_count":1,"draw_count":0,"lose_count":1,"result":[2,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":8,"opp_wizard_id":4533901,"opp_channel_uid":185481066,"opp_wizard_level":50,"opp_wizard_name":"OxY94","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494518725},{"rid":4419891,"battle_time":18761,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":4035143,"wizard_level":50,"channel_uid":182866272,"wizard_name":"Ahten","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":10,"opp_wizard_id":1370484,"opp_channel_uid":163208333,"opp_wizard_level":50,"opp_wizard_name":"cpt_n3m0","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494514421},{"rid":4417799,"battle_time":18916,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":4035143,"wizard_level":50,"channel_uid":182866272,"wizard_name":"Ahten","win_count":1,"draw_count":0,"lose_count":1,"result":[2,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":6,"opp_wizard_id":1464626,"opp_channel_uid":164090828,"opp_wizard_level":50,"opp_wizard_name":"mgyorgy24","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494514266},{"rid":4415381,"battle_time":19095,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":4035143,"wizard_level":50,"channel_uid":182866272,"wizard_name":"Ahten","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":16,"opp_wizard_id":4533901,"opp_channel_uid":185481066,"opp_wizard_level":50,"opp_wizard_name":"OxY94","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494514087},{"rid":4357663,"battle_time":23713,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":4847862,"wizard_level":50,"channel_uid":187072296,"wizard_name":"Kapaya","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":10,"opp_wizard_id":425044,"opp_channel_uid":136873074,"opp_wizard_level":50,"opp_wizard_name":"Gutshun","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494509469},{"rid":4356787,"battle_time":23780,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":4847862,"wizard_level":50,"channel_uid":187072296,"wizard_name":"Kapaya","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":14,"opp_wizard_id":33594,"opp_channel_uid":154284156,"opp_wizard_level":50,"opp_wizard_name":"Szalesz","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494509402},{"rid":4355561,"battle_time":23878,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":4847862,"wizard_level":50,"channel_uid":187072296,"wizard_name":"Kapaya","win_count":1,"draw_count":0,"lose_count":1,"result":[1,2],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":6,"opp_wizard_id":187402,"opp_channel_uid":113585338,"opp_wizard_level":50,"opp_wizard_name":"pacatka","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494509304},{"rid":4333821,"battle_time":25606,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":4247274,"wizard_level":50,"channel_uid":183427855,"wizard_name":"DevilOfHeavenn","win_count":0,"draw_count":0,"lose_count":2,"result":[2,2],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":0,"opp_wizard_id":1464626,"opp_channel_uid":164090828,"opp_wizard_level":50,"opp_wizard_name":"mgyorgy24","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494507576},{"rid":4331299,"battle_time":25816,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":4247274,"wizard_level":50,"channel_uid":183427855,"wizard_name":"DevilOfHeavenn","win_count":1,"draw_count":0,"lose_count":1,"result":[2,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":7,"opp_wizard_id":33594,"opp_channel_uid":154284156,"opp_wizard_level":50,"opp_wizard_name":"Szalesz","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494507366},{"rid":4323863,"battle_time":26422,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":4247274,"wizard_level":50,"channel_uid":183427855,"wizard_name":"DevilOfHeavenn","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":10,"opp_wizard_id":108558,"opp_channel_uid":107225759,"opp_wizard_level":50,"opp_wizard_name":"Ravenslore","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494506760},{"rid":4287185,"battle_time":29195,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":5266777,"wizard_level":50,"channel_uid":189867054,"wizard_name":"uwuwysg554","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":14,"opp_wizard_id":33594,"opp_channel_uid":154284156,"opp_wizard_level":50,"opp_wizard_name":"Szalesz","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494503987},{"rid":4282991,"battle_time":29496,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":5266777,"wizard_level":50,"channel_uid":189867054,"wizard_name":"uwuwysg554","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":10,"opp_wizard_id":425044,"opp_channel_uid":136873074,"opp_wizard_level":50,"opp_wizard_name":"Gutshun","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494503686},{"rid":4281251,"battle_time":29622,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":5266777,"wizard_level":50,"channel_uid":189867054,"wizard_name":"uwuwysg554","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":10,"opp_wizard_id":108558,"opp_channel_uid":107225759,"opp_wizard_level":50,"opp_wizard_name":"Ravenslore","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494503560},{"rid":4264599,"battle_time":30731,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":1231347,"wizard_level":50,"channel_uid":161466035,"wizard_name":"Awing","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":12,"opp_wizard_id":732196,"opp_channel_uid":157657037,"opp_wizard_level":50,"opp_wizard_name":"Godhunter","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494502451},{"rid":4098975,"battle_time":41638,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":1231347,"wizard_level":50,"channel_uid":161466035,"wizard_name":"Awing","win_count":0,"draw_count":0,"lose_count":2,"result":[2,2],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":0,"opp_wizard_id":323356,"opp_channel_uid":163351688,"opp_wizard_level":50,"opp_wizard_name":"Szilviusz1","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494491544},{"rid":4084327,"battle_time":42711,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":1231347,"wizard_level":50,"channel_uid":161466035,"wizard_name":"Awing","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":12,"opp_wizard_id":187402,"opp_channel_uid":113585338,"opp_wizard_level":50,"opp_wizard_name":"pacatka","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494490471},{"rid":4032545,"battle_time":46172,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":13776,"wizard_level":50,"channel_uid":154902363,"wizard_name":"LLSkuu","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":12,"opp_wizard_id":187430,"opp_channel_uid":132412463,"opp_wizard_level":50,"opp_wizard_name":"Tibee","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494487010},{"rid":4028409,"battle_time":46402,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":2344269,"wizard_level":50,"channel_uid":171429674,"wizard_name":"mei0404","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":16,"opp_wizard_id":309610,"opp_channel_uid":163402281,"opp_wizard_level":50,"opp_wizard_name":"Szilva14","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494486780},{"rid":4026675,"battle_time":46494,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":2344269,"wizard_level":50,"channel_uid":171429674,"wizard_name":"mei0404","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":14,"opp_wizard_id":33594,"opp_channel_uid":154284156,"opp_wizard_level":50,"opp_wizard_name":"Szalesz","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494486688},{"rid":4025385,"battle_time":46567,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":13776,"wizard_level":50,"channel_uid":154902363,"wizard_name":"LLSkuu","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":14,"opp_wizard_id":1629481,"opp_channel_uid":165345207,"opp_wizard_level":50,"opp_wizard_name":"*LeTsKo*","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494486615},{"rid":4023755,"battle_time":46653,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":2344269,"wizard_level":50,"channel_uid":171429674,"wizard_name":"mei0404","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":12,"opp_wizard_id":187430,"opp_channel_uid":132412463,"opp_wizard_level":50,"opp_wizard_name":"Tibee","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494486529},{"rid":4023255,"battle_time":46681,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":13776,"wizard_level":50,"channel_uid":154902363,"wizard_name":"LLSkuu","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":16,"opp_wizard_id":1410976,"opp_channel_uid":165483388,"opp_wizard_level":50,"opp_wizard_name":"Legolász","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494486501},{"rid":4019673,"battle_time":46895,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":2221676,"wizard_level":50,"channel_uid":170167706,"wizard_name":"Eikeldopje","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":14,"opp_wizard_id":1629481,"opp_channel_uid":165345207,"opp_wizard_level":50,"opp_wizard_name":"*LeTsKo*","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494486287},{"rid":4018149,"battle_time":46985,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":2221676,"wizard_level":50,"channel_uid":170167706,"wizard_name":"Eikeldopje","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":12,"opp_wizard_id":187430,"opp_channel_uid":132412463,"opp_wizard_level":50,"opp_wizard_name":"Tibee","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494486197},{"rid":4016567,"battle_time":47089,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":2221676,"wizard_level":50,"channel_uid":170167706,"wizard_name":"Eikeldopje","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":16,"opp_wizard_id":1410976,"opp_channel_uid":165483388,"opp_wizard_level":50,"opp_wizard_name":"Legolász","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494486093},{"rid":4016281,"battle_time":47106,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":4352889,"wizard_level":50,"channel_uid":190635719,"wizard_name":"Proxyma","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":10,"opp_wizard_id":425044,"opp_channel_uid":136873074,"opp_wizard_level":50,"opp_wizard_name":"Gutshun","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494486076},{"rid":4015043,"battle_time":47184,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":4352889,"wizard_level":50,"channel_uid":190635719,"wizard_name":"Proxyma","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":14,"opp_wizard_id":1629481,"opp_channel_uid":165345207,"opp_wizard_level":50,"opp_wizard_name":"*LeTsKo*","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494485998},{"rid":4013695,"battle_time":47270,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":4352889,"wizard_level":50,"channel_uid":190635719,"wizard_name":"Proxyma","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":16,"opp_wizard_id":1410976,"opp_channel_uid":165483388,"opp_wizard_level":50,"opp_wizard_name":"Legolász","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494485912},{"rid":4010029,"battle_time":47515,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":3253099,"wizard_level":50,"channel_uid":178457033,"wizard_name":"Raizcap","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":10,"opp_wizard_id":108558,"opp_channel_uid":107225759,"opp_wizard_level":50,"opp_wizard_name":"Ravenslore","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494485667},{"rid":4008389,"battle_time":47622,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":3253099,"wizard_level":50,"channel_uid":178457033,"wizard_name":"Raizcap","win_count":1,"draw_count":0,"lose_count":1,"result":[2,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":7,"opp_wizard_id":33594,"opp_channel_uid":154284156,"opp_wizard_level":50,"opp_wizard_name":"Szalesz","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494485560},{"rid":3997453,"battle_time":48297,"log_type":1,"match_id":10135455,"league_type":100,"wizard_id":3253099,"wizard_level":50,"channel_uid":178457033,"wizard_name":"Raizcap","win_count":2,"draw_count":0,"lose_count":0,"result":[1,1],"guild_id":96948,"guild_name":"THE EREDAR","guild_point_var":12,"opp_wizard_id":187430,"opp_channel_uid":132412463,"opp_wizard_level":50,"opp_wizard_name":"Tibee","opp_guild_id":54912,"opp_guild_name":"VulKlán","battle_end":1494484885}]}],"ts_val":1161544374,"tvalue":1494533182,"tvaluelocal":1494507982,"tzone":"Europe/Berlin"}
`

**Comment by Xzandro** [comment]
Alright, I see the problem now. There was a global guild with the same guild_id like yours. Thats a major issue and I have to restructure the database to fix those cases, which I will probably do next Sunday. I overwrite the other guild with yours for now (other guild wasnt active anyway). Its a hassle, because com2us doesnt necessarly have unique ids for each week, because they wipe their data and I never built that database for those edge cases or thought about it in the beginning. In short: it should work for your guild for now.

**Comment by torkilt** [comment]
Thanks, appreciate it =)

I have one for the suggestion box, if you ever feel like adding stuff. The guild I'm running is casual, and from that perspective two interesting metrics would be the following:

1) Missed swords, e.g. the person was on the attack team but didn't show up
2) Average bonus for chosen attacks. So I can spot if a guy did above +6. 

Have a nice weekend!

**Comment by Xzandro** [comment]
For the first idea: there already is an Absent column where you can see which member didnt use swords.

**Comment by torkilt** [comment]
Ah, it might be my data just isn't properly updated yet. I thought it recorded absence both for missed swords and not being on the team at all.
